### ISSUE TITLE
Merge into yubikey guide on NixOS

### ISSUE THREAD

**Issue by ryanorendorff** [sgillespie/nixos-yubikey-luks#2]
Hi,

This repo seems like a great automation of the process for setting up the yubikey boot. Can you edit the wiki page and add this repo as a link for the yubikey setup part?

https://nixos.wiki/wiki/Yubikey_based_Full_Disk_Encryption_(FDE)_on_NixOS

**Comment by sgillespie** [comment]
https://nixos.wiki/wiki/Yubikey_based_Full_Disk_Encryption_(FDE)_on_NixOS has been updated. Feel free to review @ryanorendorff
