### ISSUE TITLE
Yubikey Luks doesn't work currently

### ISSUE THREAD

**Issue by edmundmiller** [sgillespie/nixos-yubikey-luks#3]
I'm making an issue here in hopes that people who are interested in this will find it, rather than get lost in the nixpkgs issues.

In short, the [guide](https://nixos.wiki/wiki/Yubikey_based_Full_Disk_Encryption_(FDE)_on_NixOS) installs just fine, when I go to reboot however the yubikey and password do not work claiming they're not the correct password during stage 1. There are also some typos as of right now with the wiki guide that I'll PR that this README doesn't have.  Here is the list of things that I tried and failed.

- Yubikey 2FA and btrfs
- Yubikey 1FA and btrfs
- Plain Luks with btrfs
- Yubikey 2FA and ext4

I gave up since there wasn't a common issue and tried

- Plain Luks with ext4([This guide](https://qfpl.io/posts/installing-nixos/))

Which worked.

Relevant issues:
https://github.com/NixOS/nixpkgs/issues/13275
https://github.com/NixOS/nixpkgs/issues/15786

**Comment by edmundmiller** [comment]
Another thing that I noticed in the guide 

> This guide was tested to work on NixOS 19.03 as of July 2019. 

I was using `19.09` since I could not find an 19.03 install, and the distrowatch download for 19.03 claimed it was 19.09 when booted to the USB.

**Comment by edmundmiller** [comment]
Update this guide works properly for setting up a drive that isn't root.

**Comment by edmundmiller** [comment]
@sgillespie and to who ever it concerns

It works with a drive that is the encrypted root, however this line must be removed
```nix
    cryptoModules = ["aes" "xts" "sha512"];
```

I'll PR a fix once if anyone confirms this isn't a one off thing for me.

**Comment by sgillespie** [comment]
Just to make sure I understand, it all works as long as you remove `cryptoModules`?

EDIT: I don't see how it would have an effect as long as you would use `CIPHER=aes-xts-plain64;
HASH=sha512`. However, the default has many more and should probably be used anyways.

**Comment by edmundmiller** [comment]
@sgillespie yes correct. Exactly I don't see what it would have to do with it, it was the last place I thought to look, I accidentally forgot to add it on a build out of the 20 times I tried and it worked.

**Comment by rkrzr** [comment]
I can confirm that this fixes the problem for me as well (on two separate machines). Just removing the `cryptoModules = ...` line was enough to fix the problem, after that both the tutorial in the wiki and the README in this repo worked flawlessly. Thanks for the fix @Emiller88 !

**Comment by sgillespie** [comment]
I've addressed this here (https://github.com/sgillespie/nixos-yubikey-luks/commit/fa4e24053669394894d9052ed7a3ca934328f6e6) but not quite sure what to do with the wiki

EDIT: If you could also point out those typos I would greatly appreciate it

**Comment by rkrzr** [comment]
I have already fixed the two typos in the Wiki, that I found. I didn't see any more typos in the README in this repo.

**Comment by edmundmiller** [comment]
Awesome thanks @sgillespie and @rkrzr!

**Comment by mhuesch** [comment]
Big thank you to this thread & @sgillespie & @Emiller88 & @rkrzr. I was stuck after using https://nixos.wiki/wiki/Yubikey_based_Full_Disk_Encryption_(FDE)_on_NixOS. I used the README here to update my `hardware-configuration.nix` and now have a successfully configured `20.03` system with Yubikey 2FA! 🥳
