### ISSUE TITLE
Segfault on boot

### ISSUE THREAD

**Issue by peterwilli** [sgillespie/nixos-yubikey-luks#6]
Hey there, 

I tried the guide, both README and the NixOS wiki page. There's a weird bug that causes a segfault to appear. I filmed it on my laptop and retried it on a fresh installation on VirtualBox (with EFI mode turned on).

The first boot works, but the segfault happens somewhere after it has replaced the keys, making the next boot impossible.

I tried the latest ISO: `nixos-gnome-21.05.3957.66d6ec6ed2d-x86_64-linux.iso`

I'd love to give more info, but I don't know how, so anything that's needed I can give upon some guidance.

**Comment by ilyakooo0** [comment]
I think I had this issue when I had the "Requires touch" option set on the YubiKey. I think what happens is after you touch the YubiKey and decrypt the partition it tries to generate the next key which sends another challenge-response request and something goes wrong at this point.

Disabling "require touch" seems to have solved the problem in my case. (Or I did something slightly different during my last reinstall ¯\\_(ツ)_/¯)
